version: '3'

services:

  # TODO: Add Nginx as proxy

  postgres:
    image: postgis/postgis:13-master
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init-db/:/docker-entrypoint-initdb.d/
      - pg-data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres

volumes:
  pg-data:
